language: go
go_import_path: github.com/Leviathan1995/grape
sudo: false
go:
  - 1.8
os:
  - osx
install:
  - go get github.com/spf13/viper
  - go get github.com/golang/protobuf/proto
script:
  - go build
  - go test github.com/leviathan1995/grape/consistent
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
