// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chord.proto

/*
Package chordMessages is a generated protocol buffer package.

It is generated from these files:
	chord.proto

It has these top-level messages:
	SendIdMessage
	FingerMessage
	PredecessorMessage
	SendFingersMessage
	ChordMessage
	NetworkMessage
*/
package chordMessages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChordMessage_Command int32

const (
	ChordMessage_Ping             ChordMessage_Command = 0
	ChordMessage_Pong             ChordMessage_Command = 1
	ChordMessage_GetPredecessor   ChordMessage_Command = 2
	ChordMessage_GetId            ChordMessage_Command = 3
	ChordMessage_GetFingers       ChordMessage_Command = 4
	ChordMessage_ClaimPredecessor ChordMessage_Command = 5
	ChordMessage_GetSuccessor     ChordMessage_Command = 6
)

var ChordMessage_Command_name = map[int32]string{
	0: "Ping",
	1: "Pong",
	2: "GetPredecessor",
	3: "GetId",
	4: "GetFingers",
	5: "ClaimPredecessor",
	6: "GetSuccessor",
}
var ChordMessage_Command_value = map[string]int32{
	"Ping":             0,
	"Pong":             1,
	"GetPredecessor":   2,
	"GetId":            3,
	"GetFingers":       4,
	"ClaimPredecessor": 5,
	"GetSuccessor":     6,
}

func (x ChordMessage_Command) String() string {
	return proto.EnumName(ChordMessage_Command_name, int32(x))
}
func (ChordMessage_Command) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type SendIdMessage struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *SendIdMessage) Reset()                    { *m = SendIdMessage{} }
func (m *SendIdMessage) String() string            { return proto.CompactTextString(m) }
func (*SendIdMessage) ProtoMessage()               {}
func (*SendIdMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SendIdMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FingerMessage struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *FingerMessage) Reset()                    { *m = FingerMessage{} }
func (m *FingerMessage) String() string            { return proto.CompactTextString(m) }
func (*FingerMessage) ProtoMessage()               {}
func (*FingerMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FingerMessage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *FingerMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PredecessorMessage struct {
	Predecessor *FingerMessage `protobuf:"bytes,1,opt,name=predecessor" json:"predecessor,omitempty"`
}

func (m *PredecessorMessage) Reset()                    { *m = PredecessorMessage{} }
func (m *PredecessorMessage) String() string            { return proto.CompactTextString(m) }
func (*PredecessorMessage) ProtoMessage()               {}
func (*PredecessorMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PredecessorMessage) GetPredecessor() *FingerMessage {
	if m != nil {
		return m.Predecessor
	}
	return nil
}

type SendFingersMessage struct {
	Fingers []*FingerMessage `protobuf:"bytes,1,rep,name=fingers" json:"fingers,omitempty"`
}

func (m *SendFingersMessage) Reset()                    { *m = SendFingersMessage{} }
func (m *SendFingersMessage) String() string            { return proto.CompactTextString(m) }
func (*SendFingersMessage) ProtoMessage()               {}
func (*SendFingersMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SendFingersMessage) GetFingers() []*FingerMessage {
	if m != nil {
		return m.Fingers
	}
	return nil
}

type ChordMessage struct {
	Cmd    ChordMessage_Command `protobuf:"varint,1,opt,name=cmd,enum=chordMessages.ChordMessage_Command" json:"cmd,omitempty"`
	Cpmsg  *PredecessorMessage  `protobuf:"bytes,2,opt,name=cpmsg" json:"cpmsg,omitempty"`
	Sidmsg *SendIdMessage       `protobuf:"bytes,4,opt,name=sidmsg" json:"sidmsg,omitempty"`
	Sfmsg  *SendFingersMessage  `protobuf:"bytes,5,opt,name=sfmsg" json:"sfmsg,omitempty"`
}

func (m *ChordMessage) Reset()                    { *m = ChordMessage{} }
func (m *ChordMessage) String() string            { return proto.CompactTextString(m) }
func (*ChordMessage) ProtoMessage()               {}
func (*ChordMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ChordMessage) GetCmd() ChordMessage_Command {
	if m != nil {
		return m.Cmd
	}
	return ChordMessage_Ping
}

func (m *ChordMessage) GetCpmsg() *PredecessorMessage {
	if m != nil {
		return m.Cpmsg
	}
	return nil
}

func (m *ChordMessage) GetSidmsg() *SendIdMessage {
	if m != nil {
		return m.Sidmsg
	}
	return nil
}

func (m *ChordMessage) GetSfmsg() *SendFingersMessage {
	if m != nil {
		return m.Sfmsg
	}
	return nil
}

type NetworkMessage struct {
	Proto uint32 `protobuf:"varint,1,opt,name=proto" json:"proto,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *NetworkMessage) Reset()                    { *m = NetworkMessage{} }
func (m *NetworkMessage) String() string            { return proto.CompactTextString(m) }
func (*NetworkMessage) ProtoMessage()               {}
func (*NetworkMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NetworkMessage) GetProto() uint32 {
	if m != nil {
		return m.Proto
	}
	return 0
}

func (m *NetworkMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SendIdMessage)(nil), "chordMessages.SendIdMessage")
	proto.RegisterType((*FingerMessage)(nil), "chordMessages.FingerMessage")
	proto.RegisterType((*PredecessorMessage)(nil), "chordMessages.PredecessorMessage")
	proto.RegisterType((*SendFingersMessage)(nil), "chordMessages.SendFingersMessage")
	proto.RegisterType((*ChordMessage)(nil), "chordMessages.ChordMessage")
	proto.RegisterType((*NetworkMessage)(nil), "chordMessages.NetworkMessage")
	proto.RegisterEnum("chordMessages.ChordMessage_Command", ChordMessage_Command_name, ChordMessage_Command_value)
}

func init() { proto.RegisterFile("chord.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x6e, 0xab, 0x30,
	0x10, 0x85, 0x2f, 0x10, 0x92, 0x9b, 0x21, 0x20, 0x6b, 0x94, 0x45, 0x16, 0x57, 0xba, 0x29, 0xdd,
	0x74, 0xc5, 0x22, 0xfd, 0xdf, 0x74, 0x13, 0xa9, 0x28, 0x52, 0x5b, 0x45, 0x4e, 0x5f, 0x80, 0x62,
	0x87, 0xa2, 0x16, 0x1c, 0x61, 0x57, 0x7d, 0xe0, 0xbe, 0x48, 0x85, 0xc1, 0x29, 0xf9, 0x91, 0xba,
	0x9b, 0x19, 0xbe, 0x73, 0x66, 0x38, 0x00, 0x5e, 0xfa, 0x2a, 0x2a, 0x16, 0x6d, 0x2a, 0xa1, 0x04,
	0xfa, 0xba, 0x79, 0xe4, 0x52, 0x26, 0x19, 0x97, 0xe1, 0x7f, 0xf0, 0x57, 0xbc, 0x64, 0x0b, 0x33,
	0xc1, 0x00, 0xec, 0x9c, 0x4d, 0xac, 0xa9, 0x75, 0x36, 0xa4, 0x76, 0xce, 0xc2, 0x5b, 0xf0, 0xef,
	0xf3, 0x32, 0xe3, 0x95, 0x01, 0x26, 0x30, 0x48, 0x18, 0xab, 0xb8, 0x94, 0x2d, 0x65, 0xda, 0x56,
	0x6a, 0x6f, 0xa5, 0xcf, 0x80, 0xcb, 0x8a, 0x33, 0x9e, 0x72, 0x29, 0xc5, 0x56, 0x7f, 0x07, 0xde,
	0xe6, 0x67, 0xaa, 0x3d, 0xbc, 0xd9, 0xbf, 0x68, 0xe7, 0xac, 0x68, 0x67, 0x25, 0xed, 0x0a, 0xc2,
	0x07, 0xc0, 0xfa, 0xe2, 0x86, 0x90, 0xc6, 0xf5, 0x0a, 0x06, 0xeb, 0x66, 0x32, 0xb1, 0xa6, 0xce,
	0xaf, 0x8e, 0x06, 0x0e, 0xbf, 0x6c, 0x18, 0xcd, 0x3b, 0x20, 0x5e, 0x82, 0x93, 0x16, 0x4d, 0x00,
	0xc1, 0xec, 0x74, 0xcf, 0xa4, 0x4b, 0x46, 0x73, 0x51, 0x14, 0x49, 0xc9, 0x68, 0xcd, 0xe3, 0x35,
	0xb8, 0xe9, 0xa6, 0x90, 0x99, 0x7e, 0x7d, 0x6f, 0x76, 0xb2, 0x27, 0x3c, 0xcc, 0x81, 0x36, 0x3c,
	0x5e, 0x40, 0x5f, 0xe6, 0xac, 0x56, 0xf6, 0x8e, 0x26, 0xb1, 0xf3, 0x75, 0x68, 0xcb, 0xd6, 0xeb,
	0xe4, 0xba, 0x16, 0xb9, 0x47, 0xd7, 0x1d, 0x06, 0x44, 0x1b, 0x3e, 0x54, 0x30, 0x68, 0xef, 0xc6,
	0xbf, 0xd0, 0x5b, 0xe6, 0x65, 0x46, 0xfe, 0xe8, 0x4a, 0x94, 0x19, 0xb1, 0x10, 0x21, 0x88, 0xb9,
	0xea, 0x5c, 0x4b, 0x6c, 0x1c, 0x82, 0x1b, 0x73, 0xb5, 0x60, 0xc4, 0xc1, 0x00, 0x20, 0xe6, 0xaa,
	0x75, 0x26, 0x3d, 0x1c, 0x03, 0x99, 0xbf, 0x27, 0x79, 0xd1, 0x15, 0xb8, 0x48, 0x60, 0x14, 0x73,
	0xb5, 0xfa, 0x48, 0xdb, 0x49, 0x3f, 0xbc, 0x81, 0xe0, 0x89, 0xab, 0x4f, 0x51, 0xbd, 0x99, 0x98,
	0xc7, 0xe0, 0xea, 0xff, 0x51, 0x07, 0xed, 0xd3, 0xa6, 0x41, 0x02, 0x8e, 0xc9, 0x70, 0x48, 0xeb,
	0xf2, 0xa5, 0xaf, 0x1f, 0x9c, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x29, 0x2a, 0x44, 0xc4,
	0x02, 0x00, 0x00,
}
